### ISSUE TITLE
Remove the redundant Register dictionary

### ISSUE THREAD

**Issue by Touseefelahi** [Stira-sa/GigeVision#8]
Carefully investigate the need of duplicated dictionary, (Apparently it seems unnecessary)

If the old dictionary is proved to be useless then proceed to remove it from the library

**Comment by Touseefelahi** [comment]
@FaisalFagihi Kindly, focus on this one before the #7 issue

**Comment by FaisalFagihi** [comment]
Apparently we have two dictionaries representing the base ICategory list provided from GenIcam.

the first one:
https://github.com/Stira-sa/GigeVision/blob/5ba31f9aec9fa88616041ffdd8e6497dbaaecf87/GigeVision.Core/Services/Gvcp.cs#L102
this dictionary makes the GVCP implantation works independently from GenIcam as long as it fetches the registers addresses and and store them in string format. this approach may cause a problem with dynamic registers such as width and height when it comes to multi source ports converters.

the second one:
https://github.com/Stira-sa/GigeVision/blob/5ba31f9aec9fa88616041ffdd8e6497dbaaecf87/GigeVision.Core/Services/Gvcp.cs#L104

this dictionary should implement whatever the xml file provides; such as dynamic registers, access modes, and incremental  step for some registers.. etc.

**Comment by Touseefelahi** [comment]
@FaisalFagihi do you want me to pick one?

**Comment by FaisalFagihi** [comment]
yes, please

**Comment by Touseefelahi** [comment]
based on your comment it seems we have to go with the later one, which is : `public Dictionary<string, IPValue> RegistersDictionaryValues { get; set; } `

Once you remove the old one kindly change the name of this dictionary to RegisterDictionary only
